#!/bin/bash

alias ALIAS="alias"
alias ll="ls -l"
alias LL="ls -l"
alias gphis="history|grep " 
alias vid="vi Dockerfile"
alias CD="cd "
alias CP="cp "
alias VI="vim "
alias DOCKER="docker"
alias agi="apt-get install "
alias agc="apt-get clean "
alias DLS="dls"
alias DIL="dil"
alias ALIAS="alias"
alias GPU="gpu"
