#!/bin/bash

if [ "$2" == ""]; then
	nm=ttc
else 
	nm="$2"
fi



drm -f "$nm"
docker run -dit --name "$nm" --privileged=true --cap-add=NET_ADMIN --net=host robotica/xlbase:0.$1 /sbin/my_init -- bash -l
docker exec -d "$nm" mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
docker exec -d "$nm" echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register
docker exec -d "$nm" ssh-keygen -q -t rsa -N '' -b 4096 -C "ingted@ingted.com" -f ~/.ssh/id_rsa
docker exec -d "$nm" sed -i.bak -e s/#Port\ 22/Port\ 123/g /etc/ssh/sshd_config; cat /etc/ssh/sshd_config|grep \#Port
docker exec -d "$nm" sed -i.bak -e s/#ListenAddress\ 0\.0\.0\.0/ListenAddress\ 192\.168\.123\.95/g /etc/ssh/sshd_config; cat /etc/ssh/sshd_config|grep ListenAddress

if [ "$3" == "--nobind" ]; then
	echo No attach
else
	dbind "$nm"
fi

