#!/bin/bash

###echo "\$* : $*"
###cmd="$*"
###echo $cmd
###cmdreplaced=$(echo $cmd)
###echo $cmdreplaced


###$(echo $cmd)
###$(echo "ls /")

tmp2=$1
dhosts=$(awk '$3 == "h" {print $1}' ./hosts)
###echo $dhosts

for dh in $dhosts; do
#	ssh-copy-id root@$dh
#echo "[< Server    >]" : IP\ \ \ \ \ \ \ : $dh
	ssh root@$dh bash <<SSH_L1
		if [ "$1" == "-a" ]; then 
###			whoami
			source /root/.bashrc
			export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/alias:/usr/local/pgsql/bin 			

			ids="\$(/root/alias/dls -ll)"
			ids=(\${ids//\\n/ })

			for id in "\${ids[@]}"; do
				echo "[< Server    >]" : IP\ \ \ \ \ \ \ : $dh
				echo "[< Container >]" : ID\ \ \ \ \ \ \ : \$id
				echo "[< Container >]" : Username : \$(/usr/bin/whoami)
				echo "[< Container >]" : Hostname : \$(/bin/hostname)
				
				expath=\$(docker exec \$id 'pwd')
				echo "[< Container >]" : PATH\ \ \ \ \ : \$expath
				docker exec \$id ${*:2}
			done 
			IFS=ifsold
		else
			echo 123 
			docker exec $1 ${*:2} 
		fi 

SSH_L1

done



#sed -r 's/:Host +=> +\"[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\"/:Host               => \"\"/g' /usr/share/pcsd/ssl.rb
