#!/bin/bash

all_container=$(dls -a)
all_live=$(dls -ll)
if [ $# == 0 ]; then

	echo Please use '-a', '-f <id>'  or '-af' to remove all containers.

elif [ $# == 1 ]; then
	if [ "$1" == "-a" ]; then
		for item in ${all_container[*]}
		do
			rmv="1"
			for live in ${all_live[*]}
                	do
				test "$item" == "$live" && { rmv="0"; }
			done
			if [ "$rmv" == "1" ]; then
				docker rm $item
			fi
		done
	elif [ "$1" == "-af" -o "$1" == "-fa" ]; then
		dkill -a
		docker rm $all_container
	else
		rmv="1"
                for live in ${all_live[*]}
                do
			test "$1" != "$live" && { rmv="0"; }
                done
		if [ "$rmv" == "1" ]; then
                        docker rm $1
                fi
	fi

elif [ $# -gt 1 ]; then
	if [ "$1" == "-f" ]; then
	        dkill ${@:2}
		docker rm -f ${@:2}
	else
		for item in $@
                do
			rmv="1"
                        for live in ${all_live[*]}
                        do
                                test "$item" != "$live" && { rmv="0"; }
			done
			if [ "$rmv" == "1" ]; then
                        	docker rm $item
                	fi
                done
	fi
fi
	
