#!/bin/bash

if [ ! -e /proc/sys/fs/binfmt_misc/register ]; then mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc; fi
if [ ! -e /proc/sys/fs/binfmt_misc/CLR ]; then echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register; fi

if [ "$#" == "3" ]; then
	if [ "$1" == "-d" ]; then
		docker run -d $2 $3
	elif [ "$1" == "-r" ]; then
                docker run --rm $2 $3
	else
		docker run -it $*
	fi
elif [ "$#" == "4" ]; then
        if [ "$1" == "-d" ]; then
                docker run -d --name $2 $3 $4
        elif [ "$1" == "-r" ]; then
                docker run --rm --name $2 $3 $4
	else
		docker run -it $*
	fi
elif [ "$#" == "2" ]; then
	if [ "$1" == "-d" ]; then
                docker run -d $2 sh 
        elif [ "$1" == "-r" ]; then
                docker run --rm $2 sh
        else
		docker run -it $1 $2
	fi
elif [ "$#" == "1" ]; then
	docker run -it $1 sh
fi
