BASENAME = robotica/xlbase
BASEVERSION = latest
PACENAME = robotica/pcmk_ubuntu
PACEVERSION = latest
UTILNAME = robotica/util
UTILVERSION = latest

DB=dbuild

BEN = 1
PEN = 1
UEN = 1

SHELL = /bin/bash
