#!/bin/bash

#if [ "$1" == "" ]; then
#	echo "Container name is required!"
#	exit 999
#else
#	nm=$1
#fi

#role=$(./mgmt-xl-get-host-by-role "$1")

if [ "$1" == "" ]; then
	pgu=postgres
else
	pgu=$1
fi

./mgmt-xl-init gtm $pgu - - -
