#!/bin/bash

if [ "$1" == "" ]; then
	echo "Container name is required!"
	exit 999
else
	nm=$1
fi

if [ "$2" == "" ]; then
	echo "HOSTFILE is required! Use dexxhosts."
	HOSTF=dexxhosts
else
	HOSTF=$2
fi

hostfile=$(which "$HOSTF")
hostdata=$(cat $hostfile|awk '{print $1"\011"$2}')
hd=$(cat << EOF
127.0.0.1       localhost
127.0.1.1       localhost

#The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
$hostdata
EOF
)
hb64=$(echo "$hd"|base64)
echo $hb64

./mgmt-update-cluster-tool "$nm"
util-px "$nm" cluster-hosts.ps1 $hb64
#util-px "$nm" if\(\(dir /postgres\) -eq \$null\){\"set host failed!\"}
