#!/bin/bash

update=
nid=0
slave_or_master=m

function main () {


	./mgmt-xl-setup-nodes $force $update -n $nid --sm $slave_or_master -r gtm


}


function helptext () {
        cho ""
        echo "mgmt-xl-setup-gtm - A tool for setup a gtm node ."
        echo ""
        echo "Usage: ./mgmt-xl-setup-gtm [options]"
        echo ""
        echo "Options:"
        echo "-f, --force               If container with same name of specified one, recreate it and go ahead!!"
	echo "-u, --update		Update utility tools."
        echo ""
        exit $1

}

cnt=$#

while true ; do
        case "$1" in
        --help|-h|-\?) helptext 0;;
        -f|--force) force="-f"; shift;;
 	-u|--update) update="-u"; shift;; 
        "") break;;
        *)
                echo "[ERROR!!] Unknown option \"$1\""
                helptext 1;;
        esac
done


if [ "$cnt" == 0 ]; then 
	helptext 1
else
	main
fi
