#!/bin/bash

if [ "$1" == "" ]; then
        cluster=test
else
        cluster=$1
fi

./mgmt-xl-get-base "$cluster" 3 i

#hostfile=$(which dexxhosts)

#awk "(\$3 == \"i\") && (\$6 == \"$cluster\") {print \$1\",\"\$2}" "$hostfile"
