#!/bin/bash

echo if gpu now?
read ifgpu

if [ "$ifgpu" == "1" ] || [ "$ifgpu" == "y" ] || [ "$ifgpu" == "yes" ]; then
	gpu "installation commit"
fi

if [ "$1" == "" ]; then
        rootpath="/root"
else
        rootpath=$1
fi


if [ "$2" == "" ]; then
        cluster=test
else
        cluster=$2
fi


dhosts=$(./mgmt-xl-get-host-by-role docker $cluster)
echo "$dhosts"
for host in $dhosts; do
	cip=$(./mgmt-xl-get-ip "$host" "$cluster")
	echo $cip
	(ssh $cip << EOF
		mkdir -p "$rootpath"
		cd "$rootpath"
		rm xlbase -rf
		git clone https://github.com/ingted/xlbase.git
  		cd xlbase
	  	git checkout --track -b xlbase remotes/origin/backToOrigin
		source alias/util-disable-status 1 1 1
		echo "====\$(hostname)====="
		./make.sh
		source ~/.bashrc
		echo \$(which dexxhosts)
		echo \$PATH
		cd mgmt
		./mgmt-init-set-xl-config $cluster
		./mgmt-xl-setup-all $cluster
EOF
) &

done

