#!/bin/bash


if [ "$1" == "" ]; then
	echo "Container name is required!"
	exit 999
else
	nm=$1
fi

if [ "$2" == "" ]; then
	echo "DIRFILE is required! Use dexxpgdir."
	DIRF=dexxpgdir
else
	DIRF=$2
fi



dirfile=$(which "$DIRF")
dirdata=$(cat $dirfile)
db64=$(echo "$dirdata"|base64)
#echo $db64

echo $(date +"%T") \[\| cluster-dirs \|\]
util-px "$nm" cluster-dirs.ps1 $db64

util-px "$nm" if\(\(dir /postgres\) -eq \$null\){\"init xl dirs failed!\"}


echo $(date +"%T") \[\| service-account \|\]
util-dx "$nm" ./cluster-service-account.sh -n postgres -p "/\'],lp123"

echo $(date +"%T") \[\| service-account-permissions \|\]
util-dx "$nm" ./cluster-service-account-permissions.sh -n postgres


