#!/bin/bash

hostroles=$(which dexxhostroles)

if [ "$1" == "dn" ] || [ "$1" == "coor" ] || [ "$1" == "gtm" ] || [ "$1" == "gtmprx" ] || [ "$1" == "gtmsby" ] || [ "$1" == "docker" ]; then
	if [ "$2" == "" ]; then
		cat $hostroles|grep -E "$1\b"|awk '{print $1}'
	else
		cat $hostroles|grep -E "$1\b"|awk "\$5 == \"$2\" {print \$1}"
	fi
elif [ "$1" == "--all" ] || [ "$1" == "-a" ]; then
	cat $hostroles|awk '{print $1}'
else
	echo "wrong speficied role!"

fi
