#!/bin/bash

if [ "$2" == "" ]; then
	cluster=test
else
	cluster=$2
fi

if [ "$3" == "" ]; then
        val="\$3"
else
        val="$3"
fi

#echo "(\$1 == \"$1\") && (\$6 == \"$cluster\") {print $val}"
hostrole=$(which dexxhostroles)
awk "(\$1 == \"$1\") && (\$6 == \"$cluster\") {print $val}" $hostrole
