#!/bin/bash


if [ "$1" == "" ]; then
	echo "Container name is required!"
	exit 999
else
	nm=$1
fi

if [ "$2" == "" ]; then
	echo "DIRFILE is required! Use dexxpgdir."
	DIRF=dexxpgdir
else
	DIRF=$2
fi

if [ "$3" == "1" ]; then
        update=1
else
        update=0
fi


dirfile=$(which "$DIRF")
dirdata=$(cat $dirfile)
db64=$(echo "$dirdata"|base64)
#echo $db64

if [ "$update" == 1 ]; then 
	./mgmt-update-cluster-tool "$nm"
fi

util-px "$nm" cluster-dirs.ps1 $db64

util-px "$nm" if\(\(dir /postgres\) -eq \$null\){\"init xl dirs failed!\"}

util-dx "$nm" ./cluster-service-account.sh -n postgres -p "/\'],lp123"
util-dx "$nm" ./cluster-service-account-permissions.sh -n postgres


