#!/bin/bash

echo if gpu now?
read ifgpu

if [ "$ifgpu" == "1" ] || [ "$ifgpu" == "y" ] || [ "$ifgpu" == "yes" ]; then
	cd ..
	gpu "installation commit"
	cd mgmt
fi


if [ "$1" == "" ]; then
        rootpath="/root"
else
        rootpath=$1
fi


if [ "$2" == "" ]; then
        cluster=test
else
        cluster=$2
fi

if [ "$3" == "" ]; then
        updonly=0
else
        updonly="$3"
fi


if [ "$4" == "" ]; then
        ifmake=0
else
        ifmake="$4"
fi


dhosts=$(./mgmt-xl-get-host-by-role docker $cluster)
echo "$dhosts"
for host in $dhosts; do
	cip=$(./mgmt-xl-get-ip "$host" "$cluster")
	echo $cip
	(ssh $cip << EOF
		#rm ~/.hushlogin
		mkdir -p "$rootpath"
		cd "$rootpath"
		ls $rootpath/xlbase
		rp=\$(ls $rootpath/xlbase)
		#echo "1: $updonly" "2: $?" "3: $rp"
		if [ "$updonly" != 1 ] || [ "$?" != 0 ] || [ "\$rp" == "" ]; then
			rm xlbase -rf
			GIT_TRACE=1; GIT_CURL_VERBOSE=1
			git clone --verbose http://github.com/ingted/xlbase.git
  			cd xlbase
	  		git checkout --track -b xlbase remotes/origin/backToOrigin
		else 
			cd xlbase
			git pull
		fi
		source alias/util-disable-status 1 1 1
		echo "====\$(hostname)====="
		./make.sh
		source ~/.bashrc
		#echo "=>\$(which dexxhosts)"
		#echo "=>\$PATH"

		eexp=$(which expect)
		if [ "$eexp" == "" ]; then
			apt-get -y install expect
		fi
		if [ "$ifmake" != "0" ]; then
			./make.expect
		fi
		cd mgmt
		ls ./set.expect
		./set.expect $cluster
		#./mgmt-init-set-xl-config $cluster => change to set.expect
		#./mgmt-xl-setup-all $cluster => change to set.expect
EOF
)

done

echo eofisdsh
