#!/bin/bash



hostroles=$(which dexxhostroles)

if [ "$1" == "dn" ] || [ "$1" == "coor" ] || [ "$1" == "gtm" ] || [ "$1" == "gtmprx" ] || [ "$1" == "gtmsby" ] || [ "$1" == "docker" ]; then


	if [ "$#" == "3" ]; then
		if [ "$3" == "" ]; then
		        cluster=test
		else
		        cluster=$3
		fi

		#cat $hostroles|grep -E "$1\b"|awk "\$5 == \"$2\" {print \$1}"
		awk "(\$3 == \"$1\") && (\$6 == \"$cluster\") && (\$5 == \"$2\") {print \$1}" $hostroles
	else
		if [ "$2" == "" ]; then
		        cluster=test
		else
		        cluster=$2
		fi

		#cat $hostroles|grep -E "$1\b"|awk '{print $1}'
		awk "(\$3 == \"$1\") && (\$6 == \"$cluster\") {print \$1}" $hostroles
	fi
elif [ "$1" == "--all" ] || [ "$1" == "-a" ]; then
	if [ "$2" == "" ]; then
	        cluster=test
	else
	        cluster=$2
	fi

	awk "(\$6 == \"$cluster\") {print \$1}" $hostroles
else
	echo "wrong speficied role!"

fi
