#!/bin/bash
set "" "-c" test2 "-m" an22 "-r" dn "-s" m
source $(which dexxgnuparam) $@
dexxdir=$(dirname $(which dexxhosts))
exp=$(which resource.example)
drfil=$(which dexxhostroles)
difil=$(which dexxhostips)
hrinfo=$(./mgmt-xl-get-role $specified_cnm $cluster \$3\",\"\$5\",\"\$7)

#echo "$hrinfo"

for hi in $hrinfo; do

#	echo "$hi"
	hi_splt_by_cma=(${hi//,/ })
#	echo "${hi_splt_by_cma[0]}"
	if [ "$role" != "-" ] && [ "${hi_splt_by_cma[0]}" == "$role" ]; then
	
		hsbc=${hi_splt_by_cma[2]}
		awk "(\$2 == \"$hsbc\") && (\$5 == \"$cluster\") {print \$6\",\"\$7\",\"\$8\",\"\$9}" $difil
	fi

done

#source $(which dexxgnuparam) -c test2 -m an22 -r dn -s m
exit
role="gtm" ###cfgrole###
cnm=$(hostname)
ip="192.168.137.132" ###cfgip###
port=36666 ###cfgport###
mypath="/etc/init.d"
pglib="/usr/local/pgsql/bin"
pgdir="/postgres/gtm" ###cfgpgdir###
dexx="/root/pcmk/alias" ###cfgdexx###

cat $exp|sed -e s/###cfgrole###/role=\"gtm\"/g|sed -e s/###cfgip###/ip=\"$()\"/g|head -5


                if [ -e $exp ]; then
                        #echo $exp
                        confexp=$(cat $exp)
                        #echo "$confexp"

                        confstr=$(echo "$(eval "cluster=$cluster; host=$specified_cnm; source $(which dexxparammap); echo \"$confexp\"")")
                        #echo "$confstr"
                        conf64=$(echo "$confstr"|base64)

                        util-bpx "$specified_cnm" $pgu cluster-xl-conf.ps1 $confpath $conf64
                fi
                echo $(date +"%T") \[\| xl-conf end  \|\] @$specified_cnm $confpath


function main () {

	echo ./mgmt-xl-setup-nodes $force $update -n "$nid" --sm "$slave_or_master" -r dn  --host "$cnm"  -c "$cluster" -v "$pgver"
	./mgmt-xl-setup-nodes $force $update -n "$nid" --sm "$slave_or_master" -r dn  --host "$cnm"  -c "$cluster" -v "$pgver"


}



hosts=$(./mgmt-xl-get-host-by-role "$role" $cluster)
        for host in $hosts; do
                nid=$(./mgmt-xl-get-node-id "$host" $cluster)
                if [ "$specified_nid" == "-" ] || [ "$specified_nid" == "$nid" ]; then
                        sm=$(./mgmt-xl-get-m-or-s "$host"  $cluster)
                        if [ "$specified_sm" == "-" ] || [ "$specified_sm" == "$sm" ]; then
                                if [ "$specified_cnm" == "-" ] || [ "$specified_cnm" == "$host" ]; then

                                        conf=$(./mgmt-xl-get-confname "$host" $pgver $cluster|awk 'NR>2 && ($3 != "-") {print $1","$2","$3}'|sort|uniq|sed '/^$/d')
                                        if [ "$conf" == "invalid specified host!" ]; then
                                                echo "invalid specified host! mgmt-xl-init failed!"
                                                continue
                                        fi
                                        dir=$(echo "$conf"|awk '{split($0, a, ","); print a[1]}'|sort|uniq)

                                        echo $(date +"%T") \[\| xl-init \|\] @$host $1 $dir
                                        util-bpx "$host" $pgu cluster-xl-init.ps1 $host $1 $dir
util-bpx "$host" $pgu 
