#!/bin/bash

if [ "$2" == "" ]; then
        cluster=test
else
        cluster=$2
fi



rst=$(./mgmt-xl-check-host "$1" $cluster)
if [ "$rst" == 0 ]; then
	echo "invalid specified host!"
	exit 999
fi

hostfile=$(which dexxhosts)

awk "(\$2 == \"$1\") && (\$6 == \"$cluster\") {print \$1}" "$hostfile"
