#!/bin/bash

update=
nid=-
slave_or_master=-
cnm=-

function main () {


	./mgmt-xl-setup-nodes $force $update -n $nid --sm $slave_or_master -r gtmprx  --host $cnm


}


function helptext () {
        echo ""
        echo "mgmt-xl-setup-gtmprx - A tool for setup a xlbase gtm proxy node ."
        echo ""
        echo "Usage: ./mgmt-xl-setup-gtmprx [options]"
        echo ""
        echo "Options:"
        echo "-f, --force               If container with same name of specified one, recreate it and go ahead!!"
	echo "-u, --update		Update utility tools."
	echo "-h, --host, --hostname	Container node name."
	echo "-n, --nid, --nodeid	Container node group ID."
	echo "--sm, --slave-master	Container node group role."
        echo ""
        exit $1

}

while true ; do
        case "$1" in
        --help|-h|-\?) helptext 0;;
        -f|--force) force="-f"; shift;;
	--host|--hostname) cnm=$2; shift; shift;;
	-n|--nid|--nodeid) nid=$2; shift; shift;;
	--sm|--slave-master) slave_or_master=$2; shift; shift;;
 	-u|--update) update="-u"; shift;; 
        "") break;;
        *)
                echo "[ERROR!!] Unknown option \"$1\""
                helptext 1;;
        esac
done

main
