#!/bin/bash

 configrepo=$(which dexxconfigrepo)     ; cat  $configrepo
   hostinfo=$(which dexxhostinfo)       ; cat    $hostinfo
  hostroles=$(which dexxhostroles)      ; cat   $hostroles
      hosts=$(which dexxhosts)          ; cat       $hosts
masterslave=$(which dexxmasterslave)    ; cat $masterslave
      pgdir=$(which dexxpgdir)          ; cat       $pgdir


dexxparams
