#!/bin/bash

hostfile=
dirfile=
pguser=postgres

if [ "$5" == "1" ]; then
	update=1
else
	update=0
fi 

if [ "$update" == "1" ]; then
        echo $(date +"%T") \[\| update-cluster-tool \|\]
        ./mgmt-update-cluster-tool "$1"
fi

echo $(date +"%T") \[\| init-set-host \|\]
./mgmt-init-set-host "$1" "$hostfile"

echo $(date +"%T") \[\| init-set-xl \|\]
./mgmt-init-set-xl "$1" 9.2

echo $(date +"%T") \[\| xl-init-directories \|\]
./mgmt-xl-init-directories "$1" "$dirfile" $pguser



case $2 in
	gtm)
		./mgmt-xl-init-gtm $pguser
		;;
	gtmsby)
		./mgmt-xl-init-gtmsby $pguser
		;;            
	gtmprx)
		./mgmt-xl-init-gtmprx $1 $3 $4 $pguser
		;;
	coor)
		./mgmt-xl-init-coor $1 $3 $4 $pguser
		;;
	dn)
		./mgmt-xl-init-dn $1 $3 $4 $pguser
		;;
	*)              
esac 
