#!/bin/bash

if [ "$2" == "" ]; then
        cluster=test
else
        cluster=$2
fi


if [ ! -e ./$cluster/status/$1.status ]; then 
	echo 0
	exit 999
fi

status=$(cat ./$cluster/status/$1.status)
if [ "$status" == "" ]; then
	echo 0
else
	echo 1

fi
