#!/bin/bash

if [ "$2" == "" ]; then
        cluster=test
else
        cluster=$2
fi


if [ "$1" == "" ]; then
	pgu=postgres
else
	pgu=$1
fi


if [ "$3" == "" ]; then
        echo "pgver is required! exit"
        exit 999
else
        pgver=$3
fi


./mgmt-xl-init gtm $pgu "-" "-" "-" $cluster $pgver 0
