#!/bin/bash

if [ "$1" == "" ]; then
	cnm=-
else
	cnm=$1
fi


if [ "$2" == "" ]; then
	nid=-
else
	nid=$2
fi


if [ "$3" == "" ]; then
	sm=-
else
	sm=$3
fi


if [ "$4" == "" ]; then
	pgu=postgres
else
	pgu=$4
fi

if [ "$5" == "" ]; then
        cluster=test
else
        cluster=$5
fi


./mgmt-xl-init dn $pgu $cnm $nid $sm $cluster
