#!/bin/bash

if [ "$1" == "" ]; then
        rootpath=/root
else
        rootpath=$1
fi


if [ "$2" == "" ]; then
        cluster=test
else
        cluster=$2
fi


dhosts=$(./mgmt-xl-get-host-by-role docker $cluster)
echo "$dhosts"
for host in $dhosts; do
	cip=$(./mgmt-xl-get-ip $host $cluster)
	echo $cip
	(ssh $cip << EOF
		cd "$rootpath"
		rm xlbase -rf
		git clone https://github.com/ingted/xlbase.git
  		cd xlbase
	  	git checkout --track -b xlbase remotes/origin/backToOrigin
EOF
) &

done

