#!/bin/bash

cd ..

source alias/util-disable-status 1 1 1
./make.sh
source ~/.bashrc

cd mgmt

./mgmt-init-set-xl-config test2

expect -c "set timeout 300; spawn ./login.sh; expect {name\:}; send \"test2\\n\"; expect {Password:}; send \"/'],lp123\\n\"; expect {eofloginsh}"

echo -e "\nlogin done."

expect -c "set timeout 3600; spawn ./mgmt-init-set-dhost /test2 test2 0 0; expect {if gpu now?}; send \"0\n\"; expect {eofisdsh}" 

expect -c "set timeout 300; spawn ./clogin.sh; expect {name\:}; send \"test2\\n\"; expect {Password:}; send \"/'],lp123\\n\"; expect {eofcloginsh}"
