#!/bin/bash

./mgmt-init-set-xl-config test

expect -c "set timeout 300; spawn ./login.sh; expect {name\:}; send \"test\\n\"; expect {Password:}; send \"/'],lp123\\n\"; expect {eofloginsh}"

echo -e "\nlogin done."

expect -c "set timeout 3600; spawn ./mgmt-init-set-dhost /test test 0 0; expect {if gpu now?}; send \"0\n\"; expect {eofisdsh}" 
