#!/bin/bash

echo $PATH

dexx an22 test2 "cd /root/pcmk/; ./get-tool"
dexx an13 test2 "cd /root/pcmk/; ./get-tool"
dexx an22 test2 -d "service dn stop"
#dexx an22 test2 "setuser postgres /usr/local/pgsql/bin/pg_ctl -Z datanode -D /postgres/dn1_m/ stop"
#./mgmt-xl-init dn postgres an22 1 m test2 9.2 1
#./mgmt-xl-init dn postgres an13 1 s test2 9.2 1 1

dexx an22 test2 "service dn stop"
dexx an13 test2 "service dn stop"

./mgmt-xl-init dn postgres an22 1 m test2 9.2 1 "" 0 0 0
./mgmt-xl-init dn postgres an13 1 s test2 9.2 1 "" 1 1 0

dexx an22 test2 "chown postgres:postgres /postgres -R"
dexx an13 test2 "chown postgres:postgres /postgres -R"

dexx an22 test2 "sed -i.bak -e s/an31/an23/g /postgres/dn1_m/data/postgresql.conf"
dexx an22 test2 "sed -i.bak -e s/140/137/g /postgres/dn1_m/data/postgresql.conf"
#dexx an22 test2 "setuser postgres /usr/local/pgsql/bin/pg_ctl -Z datanode -D /postgres/dn1_m/ start"
dexx an22 test2 -d "service dn start"
dexx an22 test2 "sts=0; while [ 1 == 1 ]; do (service dn status)&&(sts=\$(echo \$?)); if [ \\\"\\\$sts\\\" == \\\"0\\\" ]; then break; fi done"
dexx an13 test2 "rm /postgres/dn1_s/data/* -rf"
dexx an13 test2 "export PGPASSWORD=\\\\\\\"/\\\\'],lp123\\\\\\\"; setuser postgres /usr/local/pgsql/bin/pg_basebackup -h an22 -U postgres -D /postgres/dn1_s/data/ -X stream -p10002 -P -w"

./mgmt-xl-init dn postgres an13 1 s test2 9.2 1 "" 1 0 1
