#!/bin/bash


echo "Opened 36666 count: $(netstat -a|grep 36666 |wc -l)"

gtmhostname=$(../mgmt/mgmt-xl-get-host-by-role gtm alpha)
gtm_ctl -Z gtm restart -D $(./monqo-conf $gtmhostname gtm) -m immediate

