#!/bin/bash

drm -f ttc
docker run -dit --name ttc --privileged --cap-add=NET_ADMIN --net=host $1 /sbin/my_init -- bash -l
docker exec -d ttc mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
docker exec -d ttc echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register
dbind ttc
