# Use phusion/baseimage as base image. To make your builds
# reproducible, make sure you lock down to a specific version, not
# to `latest`! See
# https://github.com/phusion/baseimage-docker/blob/master/Changelog.md
# for a list of version numbers.
#
#  FROM phusion/baseimage:<VERSION>

FROM phusion/baseimage:0.9.17
ENTRYPOINT /bin/bash

# Use baseimage-docker's init system.

CMD ["/sbin/my_init"]

# ...put your own build instructions here...

COPY timedatectl /usr/bin/
RUN timedatectl set-timezone  Asia/Taipei

COPY docker.list /etc/apt/sources.list.d/

RUN mkdir -p /root/Downloads; mkdir -p /root/Sources; \
	apt-get purge openjdk-7-*; \
	apt-get purge openjdk-8-*; \
	echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections; \
	echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections; \
	apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

WORKDIR /root/Sources

RUN apt-get -y update; \
	apt-get -y upgrade

RUN apt-get -y purge \
	libcurl3 libcurl3-gnutls

RUN apt-get -y upgrade; \
	apt-get -y upgrade

RUN apt-get -y install \
	ant ant-optional asciidoc autoconf automake autopoint autotools-dev \
	bison build-essential bzip2 \
	ccache cluster-glue cmake corosync-dev cvs \
	dbtoepub dbus docbook docbook-dsssl docbook-dsssl-doc docbook-xml docbook-xsl docker.io dsniff \
	flex \
	gdb gettext git git-arch git-completion git-core git-doc git-email git-svn \
	intltool \
	jade \
	kernel-package \
	libaio1 libaio-dev libboost-all-dev libbz2-dev libc++1 libc++abi1 libc++abi-dev libc++abi-test \
		libc++-dev libc++-helpers libc++-test libc6 libc6-dbg libcluster-glue-dev libcurl4-gnutls-dev \
		libdbus-1-dev libdbus-glib-1-dev libesmtp-dev libgdbm-dev \
		libglib2.0-dev libncurses5-dev libpam0g-dev libpe-status4 libpod-2-docbook-perl libqb-dev \
		libreadline-dev libselinux-dev libsgml-dtdparse-perl libsnmp-base libsnmp-dev libsqlite3-dev \
		libssl-dev libtool libxml2-dev libxml2-utils libxslt1-dev llvm \
	lm-sensors \
	multiarch-support \
	ncurses-dev ntp \
	openjade1.3 opensp \
	p7zip p7zip-full pbzip2 pkg-config publican python-lxml
