FROM robotica/xlbase:0.5.2
ADD /home/osdba/git/xlbase/pacemaker_docker_ubuntu/debs /root/debs
ADD /home/osdba/git/xlbase/pacemaker_docker_ubuntu/helper_scripts /usr/sbin
ADD /home/osdba/git/xlbase/pacemaker_docker_ubuntu/defaults/corosync.conf /etc/corosync/
