#!/bin/bash

if [ $# == 0 ]; then

	echo Please use '-a' to stop all containers.

elif [ $# == 1 ]; then

	if [ "$1" == "-a" ]; then
		if [[  $(dls -ll) ]]; then
			docker stop $(dls -ll)
		fi
	else
		docker stop $*
	fi

elif [ $# -gt 1 ]; then

        docker stop $*
fi
	
