#!/bin/bash

if [ ! -e /proc/sys/fs/binfmt_misc/register ]; then mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc; fi
if [ ! -e /proc/sys/fs/binfmt_misc/CLR ]; then echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register; fi


if [ "$#" == "1" ]; then
	docker start $1
elif [ $# -gt 1 ]; then
	for item in $@
        do
		docker start $item
	done
fi
