#!/bin/bash

if [ "$1" == "" ]; then
        nm=ttc
else
        nm="$1"
fi


if [ ! -e /proc/sys/fs/binfmt_misc/register ]; then mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc; fi
if [ ! -e /proc/sys/fs/binfmt_misc/CLR ]; then echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register; fi

docker start $nm

docker exec "$nm" bash -c "if [ -e /var/run/dbus/system_bus_socket ]; then rm /var/run/dbus/system_bus_socket; fi"
docker exec "$nm" service dbus restart

docker exec -d "$nm" bash -c " if [ ! -z /proc/sys/fs/binfmt_misc/register ]; then mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc; fi"
#docker exec -d "$nm" bash -c " if [ ! -z /proc/sys/fs/binfmt_misc/CLR ]; then echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register; fi"

docker exec "$nm" hostnamectl set-hostname "$nm"
docker exec "$nm" bash -c "echo \"$nm\" > /etc/hostname"
docker exec "$nm" bash -c 'export PS1="\[\e[0;33m\][\$(date  +\"%T\")]$PS1"'
