#!/bin/bash

if [ "$1" == "" ]; then
        nm=ttc
else
        nm="$1"
fi


if [ ! -z /proc/sys/fs/binfmt_misc/register ]; then mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc; fi
if [ ! -z /proc/sys/fs/binfmt_misc/CLR ]; then echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register; fi

docker start $nm

docker exec "$nm" rm /var/run/dbus/system_bus_socket
docker exec "$nm" service dbus restart

docker exec -d "$nm" bash -c " if [ ! -z /proc/sys/fs/binfmt_misc/register ]; then mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc; fi"
#docker exec -d "$nm" bash -c " if [ ! -z /proc/sys/fs/binfmt_misc/CLR ]; then echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register; fi"

docker exec "$nm" hostnamectl set-hostname xlbase-"$nm"
docker exec "$nm" bash -c "echo xlbase-\"$nm\" > /etc/hostname"
