#!/usr/bin/expect -f
set timeout     -1
set key  [lindex $argv 0]

spawn bash
if { $key == "" } {
	send "git pull --no-edit\n"
	sleep 1
	send "yes\n"
} else {
	send "eval `ssh-agent` ; ssh-add $key; git pull --no-edit\n"
}
sleep 1
#send "yes\n"
set prompt 1
expect {
    -re {\(yes/no\)\? $} {
	puts "\nBUFFER:\n\[\[\[\n$expect_out(buffer)\n]]]\n"
	sleep 1
	puts "\n1=======================\n"
	exp_send "yes\n"
	sleep 1
	exp_continue
    }
    "Enter passphrase for" {
	puts "\nBUFFER:\n\[\[\[\n$expect_out(buffer)\n]]]\n"
	sleep 1
	puts "\n=======================\n"
	exp_send "\n"
	#exp_continue

	exp_continue	
    }
    -re {((.|\[\[:space:\]\])*(\\$|#))? $} {
	puts "\nBUFFER:\n\[\[\[\n$expect_out(buffer)\n]]]\n"
	if { [expr {$prompt > 5}] eq 1 } {
		exp_send "aa=\"agentttc\"\"ttcagent\"; echo \$aa\n"
	} else {
		exp_send "\n"
		set prompt [ expr { $prompt + 1 } ]
		exp_continue
	}
    }
}
expect {
    {agentttcttcagent} {
    	exp_send "echo 0; exit\n"
    }
    
    eof {
    	exp_send "echo 1; exit\n"
    }	
}
expect eof
