#!/bin/bash

git config --global user.name "anibal.yeh"
git config --global user.email anibal.yeh@gmail.com
git config --global push.default simple

if [ -e exped ]; then
	rm exped
fi 

git add *
if [ "$1" == "" ]; then
	git commit --no-edit --allow-empty-message -m
else
	git commit --no-edit --message="$1"
fi

#expect -c "set timeout 360; spawn git push; expect {The upstream branch of your current branch does not match.*} 

pushout=$((git push) 2>&1)
if [ $? != 0 ]; then
	$(echo $pushout|sed -r 's/.*upstream\ branch\ on\ the\ remote,\ use\ (.*)+?\ To\ push.*/\1/g')
fi
