#!/bin/bash

git config --global user.name "anibal.yeh"
git config --global user.email anibal.yeh@gmail.com

git add .
if [ "$1" == "" ]; then
	git commit --no-edit --allow-empty-message -m
else
	git commit --no-edit --message="$1"
fi
git push
