#!/bin/bash

#echo "\$* : $*"

if [ "$1" == "-a" ]; then

	for id in $(dls -ll); do
		echo "$id: "
		docker exec $id ${*:2}
	done
else
	rtn=$(docker exec $1 pash -c ${*:2})
	#testrtn=$(echo $rtn|grep "Error response from daemon")
	#if [ "$testrtn" == "" ]; then 
	#	echo "Try util..."
	#	rtn=$(docker exec util pash -c $*)
	#fi
	#echo $rtn
	#echo -e "---\n"
	echo "$rtn"|sed '1d'
fi
