#!/bin/bash

#echo "\$* : $*"

pash=$(docker exec $1 which pash)

if [ "$1" == "-a" ]; then

	for id in $(dls -ll); do
		echo "$id: "
		docker exec $id mono $pash -c cd /root/pcmk/cluster/\; ${*:2}
	done
else
	rtn=$(docker exec $1 mono $pash -c cd /root/pcmk/cluster/\; ${*:2})
	#testrtn=$(echo $rtn|grep "Error response from daemon")
	#if [ "$testrtn" == "" ]; then 
	#	echo "Try util..."
	#	rtn=$(docker exec util pash -c $*)
	#fi
	#echo $rtn
	#echo -e "---\n"
	echo "$rtn"|sed '1d'
fi
