#!/bin/bash
if [ "$1" == "" ]; then
        hostyp=h
else
        hostyp="$1"
fi

if [ "$2" == "" ]; then
        extyp="-a"
else
        extyp="$2"
fi

if [ "$3" == "" ]; then
        cluster=test
else
        cluster="$3"
fi


dcmd=${*:4}
echo "distributed command: $dcmd"
hostfil=$(which dexxhosts)
dhosts=$(awk "(\$3 == \"$hostyp\") && (\$6 == \"$cluster\") {print \$2\",\"\$1}" $hostfil)
#echo "awk \"(\\\$3 == \\\"$hostyp\\\") && (\\\$6 == \\\"$cluster\\\") {print \\\$2\\\",\\\"\\\"$1\\\"}\" $hostfil"



#echo ===========\$dhosts============
#echo  $dhosts
#echo ===========\$cnms\ \ ============
#echo  $cnms
#echo ===============================


for dhi in $dhosts; do

	dhtmp=(${dhi//\,/ })
        dh=${dhtmp[1]}
	echo @ $dh
        dnm=${dhtmp[0]}
        cnms=$(awk "(\$4 == \"$dnm\") && (\$6 == \"$cluster\") {print \$2}" $hostfil)
	#echo $cnms
	cips=$(awk "(\$4 == \"$dnm\") && (\$6 == \"$cluster\") {print \$1}" $hostfil)
	#echo $cips
	ssh root@$dh bash <<'SSH_L1'
		echo "$PATH" > ~/PATH.TMP
		#echo "$PATH"		


SSH_L1

	ssh root@$dh bash << SSH_L1
		export PATH=\$(cat ~/PATH.TMP) 
		export PATH=\$PATH:/root/xlbase/alias
		dhosts_o="$dhosts"
		dhosts=(\${dhosts_o//\\\n/ })
		#echo =====\\\$dhosts in remote ========
		#echo ==echo \$dhosts
		#echo ==echo ===============================
		cnms_o="$cnms"
		cnms_r=(\${cnms_o//\\\n/ })
		cips_o="$cips"
		cips_r=(\${cips_o//\\\n/ })
		#echo =====\\\$cnms_r remote ========
		#echo \${cnms_r[2]}
		#echo ===============================
			echo Docker Host Mode: \(Please specify docker container ID\)
			array_contains2() {
			    local array="\$1[@]"
			    local seeking="\$2"
			    local in=1
			    for element in \${!array}; do
			        if [ "\$element" == "\$seeking" ]; then
			            in=0
			            break
			        fi
			    done
			    return \$in
			}
			dlss=\$(\$(which dls) -ll)
			dlsss=(\${dlss//\\\n/ })			
			#echo =====\\\$dlsss in remote =========
                	#echo \$dlsss
                	#echo \$cnms_r
			#echo \${dlsss[0]}
			#echo $extyp
                	#echo ===============================

			#Do not support IP so far...
			if [[ \$(array_contains2 dlsss "$extyp" && echo 1 || echo 0) == 1 ]] || [[ \$(array_contains2 cips_r "$extyp" && echo 1 || echo 0) == 1 ]] || [[ \$(array_contains2 cnms_r "$extyp" && echo 1 || echo 0) == 1 ]]; then 
			#if [[ \$(array_contains2 dlsss "$extyp" && echo 1 || echo 0) == 1 ]] || [[ \$(array_contains2 cnms_r "$extyp" && echo 1 || echo 0) == 1 ]]; then 
			#if [[ \$(array_contains2 cnms_r "$extyp" && echo 1 || echo 0) == 1 ]]; then 
				extypp=$(./mgmt-xl-get-host-by-ip "$extyp" "$cluster")
				#echo "->\$extypp"
				if [ "\$extypp" != "" ]; then extyp=\$extypp; else extyp=\$extyp; fi
				#echo \$extyp
				docker exec \$extyp bash -c '${*:4}'
			else
				#echo \$(\$(which dls) -ll)
				#echo $extyp
				#echo \$(array_contains2 \$(\$(which dls) -ll) "$extyp")
				echo Wrong container ID!
			fi

SSH_L1

done



#sed -r 's/:Host +=> +\"[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\"/:Host               => \"\"/g' /usr/share/pcsd/ssl.rb
